### ISSUE TITLE
1*1 conv  branch adds into MSRB?

### ISSUE THREAD

**Issue by IPNUISTlegal** [MIVRC/MSRN-PyTorch#1]
![image](https://user-images.githubusercontent.com/35527568/46183280-c9ee7900-c302-11e8-88c9-46d0f94528b3.png)
![image](https://user-images.githubusercontent.com/35527568/46183293-de327600-c302-11e8-8449-41681b68b6da.png)
Have your ever  tried 1x1 conv  to Multi-scale Residual Block(MSRB), just like the same way as 3x3 conv or 5x5 conv? Is it preform better?
thx a lot.

**Comment by CV-JunchengLi** [comment]
![image](https://user-images.githubusercontent.com/38713974/46905475-eefc0200-cf26-11e8-8136-210f056728d5.png)
We considered it, but we finally chose to put 1x1 conv at the end of the block, which can reduce the parameters of the block, and also can achieve features fusion between different scales.
Of course, introducing 1x1 conv, or even 7x7 conv to MSRB as you said, is may preform better.
