### ISSUE TITLE
About log.txt file

### ISSUE THREAD

**Issue by Jee-King** [MIVRC/MSRN-PyTorch#11]
Hi, thanks for your sharing. It's a wonderful job.
My own training is not efficient, so could you provide any _log.txt_ file? Such as MSRN_X2.
This is my e-mail, 1406011307@qq.com. Thanks a lot.

**Comment by CV-JunchengLi** [comment]
Thank you for your attention.
The file has been sent to your mailbox.

**Comment by Jee-King** [comment]
Thank you very much!

**Comment by Ji-qing** [comment]
您好，我还有一个问题，就是在测量bicubic的psnr值具体是怎么测得。我是这样测的，比如说测试Set14 x2  的bicubic的值， 我是把Set5的GT图像先进行modcrop，然后再bicubic插值减小、放大，测量psnr的结果。matlab代码如下:
```
    scale = 2; 
    im_gt = modcrop(im_gt, scale);
    im_bic = imresize(im_gt, 1/scale, 'bicubic');
    im_bic = imresize(im_pre, scale, 'bicubic');
    if size(im_pre,3) > 1
        im_gt = rgb2ycbcr(im_gt); im_gt = im_gt(:, :, 1);
        im_pre = rgb2ycbcr(im_pre); im_pre = im_pre(:, :, 1);
    end
    psnr1(i) = psnr(im_gt,im_pre);
```
测得Set14 的 psnr值是30.00 ssim值是0.8684， 跟文章有一点差距

**Comment by CV-JunchengLi** [comment]
你可以参考这两个文件
https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Test/Prepare_TestData_HR_LR.m <https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Test/Prepare_TestData_HR_LR.m>

https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Test/Evaluate_PSNR_SSIM.m <https://github.com/MIVRC/MSRN-PyTorch/blob/master/MSRN/Test/Evaluate_PSNR_SSIM.m>

第一个文件是用来处理LR图像和HR图像的，第二个文件是用来测试PSNR和SSIM的

> 在 2019年3月16日，下午4:39，Jiqing Zhang <notifications@github.com> 写道：
> 
> im_gt

**Comment by Jee-King** [comment]
嗯呢 谢谢
