### ISSUE TITLE
What about an 8x test dataset

### ISSUE THREAD

**Issue by JiliGH** [MIVRC/MSRN-PyTorch#15]
Can you share 8 times the code of sample under the picture? 
What do you do when the sample size is inconsistent?

**Comment by CV-JunchengLi** [comment]
Can you describe your problem more clearly?
I am not very clear about your problem.

**Comment by JiliGH** [comment]
How to process the 8x LR image in DIV2K datasets when training model ?

**Comment by CV-JunchengLi** [comment]
Use the MSRN-PyTorch/MSRN/Test/Prepare_TestData_HR_LR.m file to generate 8x LR training images, just like the test image generation, only need to change the dataset path and save path.
