### ISSUE TITLE
关于训练曲线

### ISSUE THREAD

**Issue by sxd0071** [MIVRC/MSRN-PyTorch#16]
您好，我想请问一下论文里的性能对比曲线图，您是怎么画出来的？

**Comment by CV-JunchengLi** [comment]
网络采用一个相同的backbone，然后分别加入不同的block，测试出psnr，再用pythin画出结果。

**Comment by sxd0071** [comment]
@CV-JunchengLi  是保存好每张曲线图，最后再合并到一张图做对比吗

**Comment by CV-JunchengLi** [comment]
是的，分别训练，分别保存各个模型的每一次迭代结果，最后在一张图上绘制出。不过现在应该也有很多库或者插件是支持多模型同时训练，并在一张图上实时绘制对比结果的。

**Comment by sxd0071** [comment]
@CV-JunchengLi 不好意思哦，那你们是用什么软件提取出psnr曲线图的那么多数据点的，还是matlab直接提取呢？

**Comment by sxd0071** [comment]
@CV-JunchengLi 就是我不太理解怎么把所有曲线合并到一张图里作对比

**Comment by CV-JunchengLi** [comment]
我们是直接用Python读取结果画的

**Comment by sxd0071** [comment]
@CV-JunchengLi 已解决 感谢
