### ISSUE TITLE
training on Y channel

### ISSUE THREAD

**Issue by sureJ0824** [MIVRC/MSRN-PyTorch#19]
sorry but I have some questions that need your help.
I wanna train my own model based EDSR on Y channel, and my evaluation on DIV2K is rising，but when I evaluate on Set5, Set14, compared with the model training on RGB, the result is lower，Do you know why ?
Thanks a lot anyway 
Looking forward to your reply

**Comment by CV-JunchengLi** [comment]
Can you describe your experiment in more detail and provide your results？
