### ISSUE TITLE
验证集

### ISSUE THREAD

**Issue by Nibbles55** [MIVRC/MSRN-PyTorch#21]
你好，我想问一下，在训练网络时，我把验证集换成Set5或者Set14得出来的PSNR的结果曲线，和用Matlab测试Set5和Set14数据集得出来的PSNR值的结果差别很大，这是什么原因呢？

**Comment by CV-JunchengLi** [comment]
您好，训练代码和验证代码中PSNR的测试是对图像的RGB三个通道进行测试的。而Matlab的测试代码是为了与大家论文中的测试方法保持一致，所以是对Y通道进行测试的。 所以二者在测试的时候得到的结果是不一样的。 验证集的目的是为了判断网络是否收敛以及是否过拟合等，所以对RGB通道进行测试还是Y通道进行测试，都是可行的。如果你要让二者保持一致，你可以改训练和验证的代码，使其也测Y通道。

**Comment by Nibbles55** [comment]
好的，非常感谢！
