### ISSUE TITLE
模型参数量

### ISSUE THREAD

**Issue by Nibbles55** [MIVRC/MSRN-PyTorch#22]
您好，我看您论文里写的模型参数量Parameters为6.3M，但是我复现网络得出来的Parameters结果是24.3M。请问一下，您是怎么得出这个结果的呢？

**Comment by CV-JunchengLi** [comment]
24.3M是保存下来的.pt文件所需要的储存空间大小，6.3M是模型的参数量，其中M代表的是Million。 请认真区分二者的区别。

**Comment by Nibbles55** [comment]
好的，十分感谢ヽ(￣▽￣)و。
