### ISSUE TITLE
PSNR测试与论文结果差距过大？

### ISSUE THREAD

**Issue by FBLeee** [MIVRC/MSRN-PyTorch#25]
您好，我用了所有您项目提供的代码、数据集。没有改变任何参数，但是我用python代码测试出来的结果（也是用您的x2训练模型）但是在set5上的平均PSNR=35.86618025   与 您论文提供的PSNR = 38.08  差距过大！请问这是什么原因呢？

**Comment by CV-JunchengLi** [comment]
说明你自己弄错了呗，自己自身找原因
