### ISSUE TITLE
Testing on patches

### ISSUE THREAD

**Issue by harish-vnkt** [MIVRC/MSRN-PyTorch#26]
Hi, during testing on the benchmark datasets, do you use the low resolution patches or do you use the whole image?

**Comment by CV-JunchengLi** [comment]
We use the whole image during testing. 

In order to reduce memory and training time, the patch strategy is used during training, but not used during testing.

**Comment by harish-vnkt** [comment]
Thank you! I have another question. Is it possible that some of the pixels of an image might not get selected in a patch during the entire training phase?

**Comment by CV-JunchengLi** [comment]
It's possible.
The strategy of randomly selecting patches is used during training, so there is such a possibility.
