### ISSUE TITLE
关于论文中4.4 Qualitative Analysis 的一些疑问

### ISSUE THREAD

**Issue by Zamirquito** [MIVRC/MSRN-PyTorch#3]
@MIVRC-CV   @CV-JunchengLi  @FYXX  ，你们好，这篇文章的idea令我眼前一亮，融合不同尺度的feature来得到更好的feature map。 不过我有一些小疑问。。。

在Section 4.4 的 Benefit of MSRB 中，你们提到对比了不同的feature extraction 模块，你们的结果表现十分恐怖。。。但是你们的MSRB是由多路网络组成， 一个MSRB中相当于3层网络，我们知道res block一般是一两层，例如EDSR中就是3x3conv-relu-3x3conv, 而dense block 一般是多个conv-relu堆叠然后最后加一个1x1conv。但是文中没有给出你们在对比中使用的单个res block 和dense block的具体参数，所以我想询问一下在你们的对比实验中对于这两个模块的具体设置是怎么样的？你们在对比实验设计的时候有没有考虑过单个block的参数量呢？谢谢！

**Comment by CV-JunchengLi** [comment]
你好，感谢你对我们论文的关注。你的理解是正确的。我们当时只对比了单个block之间性能的差异，这些不同的block采用的是原论文各个block的网络设计和参数设置。这确实会导致其参数量不同，而进一步影响其性能。后期，我们会进一步探讨在等量参数情况下不同block的性能分析。我们的一个新工作已经意识到了你提到的这个问题，并且做了详细的实验分析，新论文很快将公开。

**Comment by Zamirquito** [comment]
谢谢你的耐心解答，期待你们的新工作。😄
