### ISSUE TITLE
Issue about Manga109

### ISSUE THREAD

**Issue by YongboLiang** [MIVRC/MSRN-PyTorch#6]
Hi, I have another doubt about Manga109 dataset. The size of image in Manga109 is 1654✖1170. If only the right half of the picture is used to test, the size of SR_x2 should be 827✖1170. However, the size of images in your test results is 826✖1170. I want to know how do you get HR images from Manga109? Only get（829:1654, :, :) from Manga109 or other strategy?

Could you share processed HR_Manga109? Especially the image named PrayerHaNemurenai. Mine is damaged. such as:
![A S](https://raw.githubusercontent.com/YongboLiang/MyImages/master/images/PrayerHaNemurenai.jpg)

Best.

**Comment by CV-JunchengLi** [comment]
Sorry, I didn't understand what you mean.
We checked the image of PrayerHaNemurenai.png.
The size of this image is 742 x 1072 (HR), and the size of the corresponding LR image is 371 x 536.

PrayerHaNemurenai_HR_x2.png
![prayerhanemurenai_hr_x2](https://user-images.githubusercontent.com/38713974/50290215-ecc59f00-04a5-11e9-8599-47c89be940a9.png)

PrayerHaNemurenai_LRBI_x2.png
![prayerhanemurenai_lrbi_x2](https://user-images.githubusercontent.com/38713974/50290246-01a23280-04a6-11e9-9430-3b3528dbc7c4.png)

There are some images in the test datasets that cannot be divisible by the scale, so you should use the MSRN-PyTorch/MSRN/Test/Prepare_TestData_HR_LR.m  file to preprocess the HR and LR files.

Best

**Comment by YongboLiang** [comment]
之前没有描述好我想问的问题，不好意思啊。

我是在向Manga109所有者申请下载后，从他们给的下载链接里下载的图片。数据集总共是3.8G，共109个文件夹。我从每个文件夹中提取第一张图片作为超分辨重建测试数据集--Manga109。
但是这样得到的每张图片的分辨率是1654✖1170，你的测试集里的图片的大小基本是826✖1170的。

![A S](https://raw.githubusercontent.com/YongboLiang/MyImages/master/images/manga109g.bmp)
![A S](https://raw.githubusercontent.com/YongboLiang/MyImages/master/images/manga109c.bmp)

所以我想知道你是怎么处理数据集来得到Manga109测试集的。因为我发现你的测试集基本是我的现在测试集的右边半部分，所以想是不是选取图像的右半部分，即（829:1654, :, :）。
另外我下载的数据集里PrayerHaNemurenai这张图片损坏了，所以想请你分享下这张图片。如果能分享你制作的全部的Manga109测试集就更好啦~谢谢啦~~

![A S](https://raw.githubusercontent.com/YongboLiang/MyImages/master/images/manga109e.bmp)
![A S](https://raw.githubusercontent.com/YongboLiang/MyImages/master/images/manga109a.bmp)

**Comment by CV-JunchengLi** [comment]
关于Manga109，我们下载到的就是只有右半部分的~
所有的测试数据集（未经处理的）都可以从我们提供的以下链接下载到：
https://www.jianguoyun.com/p/DaSU0L4Q19ySBxi_qJAB

我们提供了Set5， Set14， BSDS100， Urbanq100 和 Manga109 五种测试集。

祝好~

**Comment by YongboLiang** [comment]
got it. Thanks again~

**Comment by GoingCrazyWoo** [comment]
@YongboLiang 你好，我想知道怎么才能够申请到Manga109数据集（申请过一次但是没有收到）
