### ISSUE TITLE
Is pretrain model available?

### ISSUE THREAD

**Issue by hih70** [MIVRC/MSRN-PyTorch#8]
Hello, 
Thank you for this impressive work.
I wonder that any pretrain model available to reproduce paper results?
Thank you

**Comment by CV-JunchengLi** [comment]
Of course, we provide all pre-train models in this project.
You can find in MSRN-PyTorch/MSRN/Test/model/
![image](https://user-images.githubusercontent.com/38713974/50877633-a9f44880-140d-11e9-88ad-ea4676691aab.png)
Thank you for your attention.
